services:
  op-proxy:
    image: caddy:2-alpine
    restart: always
    environment:
      - SERVICE_FQDN_OPENPANEL_80
      - DOMAIN_NAME=${OPENPANEL_HOST}
    command: >
      sh -c "
        envsubst < /etc/caddy/Caddyfile.template > /etc/caddy/Caddyfile
        caddy run --config /etc/caddy/Caddyfile
      "
    volumes:
      - op-proxy-data:/data
      - op-proxy-config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile.template
    depends_on:
      - op-dashboard
      - op-api

  op-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - op-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # Uncomment to expose ports
    # ports:
    #   - 5432:5432

  op-kv:
    image: redis:7.2.5-alpine
    restart: always
    volumes:
      - op-kv-data:/data
    command: ["redis-server", "--maxmemory-policy", "noeviction"]
    # Uncomment to expose ports
    # ports:
    #   - 6379:6379

  op-geo:
    image: observabilitystack/geoip-api:latest
    restart: always

  op-ch:
    image: clickhouse/clickhouse-server:24.3.2-alpine
    restart: always
    volumes:
      - op-ch-data:/var/lib/clickhouse
      - op-ch-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/op-config.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/op-user-config.xml:ro
      - ./clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", 'clickhouse-client --query "SELECT 1"']
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  op-api:
    image: lindesvard/openpanel-api:latest
    restart: always
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL to be ready...'
        while ! nc -z op-db 5432; do
          sleep 1
        done
        echo 'PostgreSQL is ready'

        echo 'Waiting for ClickHouse to be ready...'
        while ! nc -z op-ch 8123; do
          sleep 1
        done
        echo 'ClickHouse is ready'

        echo 'Running migrations...'
        CI=true pnpm -r run migrate:deploy

        pnpm start
      "
    depends_on:
      - op-db
      - op-ch
      - op-kv
      - op-geo
    environment:
      - NODE_ENV="production"
      - SELF_HOSTED="true"
      - GEO_IP_HOST="http://op-geo:8080"
      - BATCH_SIZE="5000"
      - BATCH_INTERVAL="10000"
      - ALLOW_REGISTRATION="false"
      - ALLOW_INVITATION="true"
      - REDIS_URL="redis://op-kv:6379"
      - CLICKHOUSE_URL="http://op-ch:8123/openpanel"
      - DATABASE_URL="postgresql://postgres:postgres@op-db:5432/postgres?schema=public"
      - DATABASE_URL_DIRECT="postgresql://postgres:postgres@op-db:5432/postgres?schema=public"
      - NEXT_PUBLIC_DASHBOARD_URL=${OPENPANEL_HOST}
      - NEXT_PUBLIC_API_URL=${OPENPANEL_HOST}/api
      - COOKIE_SECRET=${SERVICE_PASSWORD_32_SECRET}

  op-dashboard:
    image: lindesvard/openpanel-dashboard:latest
    restart: always
    depends_on:
      - op-api
    environment:
      - NODE_ENV="production"
      - SELF_HOSTED="true"
      - GEO_IP_HOST="http://op-geo:8080"
      - BATCH_SIZE="5000"
      - BATCH_INTERVAL="10000"
      - ALLOW_REGISTRATION="false"
      - ALLOW_INVITATION="true"
      - REDIS_URL="redis://op-kv:6379"
      - CLICKHOUSE_URL="http://op-ch:8123/openpanel"
      - DATABASE_URL="postgresql://postgres:postgres@op-db:5432/postgres?schema=public"
      - DATABASE_URL_DIRECT="postgresql://postgres:postgres@op-db:5432/postgres?schema=public"
      - NEXT_PUBLIC_DASHBOARD_URL=${OPENPANEL_HOST}
      - NEXT_PUBLIC_API_URL=${OPENPANEL_HOST}/api
      - COOKIE_SECRET=${SERVICE_PASSWORD_32_SECRET}

  op-worker:
    image: lindesvard/openpanel-worker:latest
    restart: always
    depends_on:
      - op-api
    environment:
      - NODE_ENV="production"
      - SELF_HOSTED="true"
      - GEO_IP_HOST="http://op-geo:8080"
      - BATCH_SIZE="5000"
      - BATCH_INTERVAL="10000"
      - ALLOW_REGISTRATION="false"
      - ALLOW_INVITATION="true"
      - REDIS_URL="redis://op-kv:6379"
      - CLICKHOUSE_URL="http://op-ch:8123/openpanel"
      - DATABASE_URL="postgresql://postgres:postgres@op-db:5432/postgres?schema=public"
      - DATABASE_URL_DIRECT="postgresql://postgres:postgres@op-db:5432/postgres?schema=public"
      - NEXT_PUBLIC_DASHBOARD_URL=${OPENPANEL_HOST}
      - NEXT_PUBLIC_API_URL=${OPENPANEL_HOST_API}
      - COOKIE_SECRET=${SERVICE_PASSWORD_32_SECRET}
